# model
model_name_or_path:  meta-llama/Llama-2-13b-chat-hf
adapter_name_or_path: saves/save_folder/
reward_model: saves/save_folder_rm/

# method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# dataset
dataset: fiqa_train
template: llama2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/save_folder_iteration
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.00001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0
fp16: true

# generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
